# Generated by Django 5.2.6 on 2025-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('contant', models.TextField(default='')),
                ('number', models.FloatField(default='')),
                ('date', models.DateField(default='datetime.date.today')),
            ],
        ),
    ]
