# Generated by Django 5.2.6 on 2025-09-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='date',
            new_name='datep',
        ),
    ]
